server:
  port: 8081

spring:
  r2dbc:
    url: r2dbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:bookswap_auth}
    username: ${DB_USER:bookswap}
    password: ${DB_PASSWORD:bookswap}

  flyway:
    enabled: true
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:bookswap_auth}
    user: ${DB_USER:bookswap}
    password: ${DB_PASSWORD:bookswap}
    schemas: public
    locations: classpath:db/migration
    baseline-on-migrate: true

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: false
  servers:
    - url: http://localhost:8080
      description: Gateway

logging:
  level:
    dev.petr.auth: DEBUG
    io.r2dbc.postgresql.QUERY: DEBUG