server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:bookswap_exchanges}
    username: ${DB_USER:bookswap}
    password: ${DB_PASSWORD:bookswap}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    schemas: public
    locations: classpath:db/migration
    baseline-on-migrate: true

  kafka:
    bootstrap-servers: kafka-1:29092,kafka-2:29092,kafka-3:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full
  circuitbreaker:
    enabled: true

resilience4j:
  circuitbreaker:
    instances:
      bookService:
        sliding-window-size: 10
        sliding-window-type: COUNT_BASED
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30000
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true
        record-exceptions:
          - feign.FeignException
          - java.net.ConnectException
        ignore-exceptions:
          - java.lang.IllegalArgumentException

  retry:
    instances:
      bookService:
        max-attempts: 3
        wait-duration: 1000

  timelimiter:
    instances:
      bookService:
        timeout-duration: 5s

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,circuitbreakers,circuitbreakerevents
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: false
  servers:
    - url: http://localhost:8080
      description: Gateway

logging:
  level:
    dev.petr.exchange: DEBUG
    dev.petr.exchange.client: DEBUG
