server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:bookswap_exchanges}
    username: ${DB_USER:bookswap}
    password: ${DB_PASSWORD:bookswap}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    schemas: public
    locations: classpath:db/migration
    baseline-on-migrate: true

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 1
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
        slowCallRateThreshold: 100
        slowCallDurationThreshold: 2s
        ignoreExceptions:
          - feign.FeignException$BadRequest
          - feign.FeignException$Unauthorized
          - feign.FeignException$Forbidden
          - feign.FeignException$NotFound
          - feign.FeignException$MethodNotAllowed
          - feign.FeignException$Conflict
          - feign.FeignException$UnprocessableEntity
    instances:
      bookService:
        baseConfig: default
        slidingWindowSize: 10
        minimumNumberOfCalls: 1
        waitDurationInOpenState: 5s
        failureRateThreshold: 50

feign:
  circuitbreaker:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
      book-service:
        connectTimeout: 2000
        readTimeout: 2000

  retry:
    instances:
      bookService:
        max-attempts: 3
        wait-duration: 1000

  timelimiter:
    instances:
      bookService:
        timeout-duration: 5s

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,circuitbreakers,circuitbreakerevents
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: false
  servers:
    - url: http://localhost:8080
      description: Gateway

logging:
  level:
    dev.petr.exchange: DEBUG
    dev.petr.exchange.client: DEBUG
