server:
  port: 8086

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:bookswap_files}
    username: ${DB_USER:bookswap}
    password: ${DB_PASSWORD:bookswap}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    schemas: public
    locations: classpath:db/migration
    baseline-on-migrate: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  kafka:
    bootstrap-servers: kafka-1:29092,kafka-2:29092,kafka-3:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

file:
  storage:
    location: /app/uploads
    max-size: 10485760

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: false
  servers:
    - url: http://localhost:8080
      description: Gateway

logging:
  level:
    dev.petr.file: DEBUG
    org.springframework.kafka: INFO