server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/v1/auth/**

        - id: book-service
          uri: lb://book-service
          predicates:
            - Path=/api/v1/books/**,/api/v1/genres/**
          filters:
            - JwtAuthenticationFilter

        - id: exchange-service
          uri: lb://exchange-service
          predicates:
            - Path=/api/v1/exchanges/**
          filters:
            - JwtAuthenticationFilter

        - id: publication-service
          uri: lb://publication-service
          predicates:
            - Path=/api/v1/publications/**
          filters:
            - JwtAuthenticationFilter

      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:4200}"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              - PATCH
            allowedHeaders: "*"
            allowCredentials: true
            exposedHeaders:
              - X-Total-Count
              - Authorization
            maxAge: 3600

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,gateway
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true

logging:
  level:
    dev.petr.gateway: DEBUG
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: INFO