server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/v1/auth/**

        - id: book-service
          uri: lb://book-service
          predicates:
            - Path=/api/v1/books/**,/api/v1/genres/**
          filters:
            - JwtAuthenticationFilter

        - id: exchange-service
          uri: lb://exchange-service
          predicates:
            - Path=/api/v1/exchanges/**
          filters:
            - JwtAuthenticationFilter

        - id: publication-service
          uri: lb://publication-service
          predicates:
            - Path=/api/v1/publications/**
          filters:
            - JwtAuthenticationFilter

        - id: auth-service-swagger
          uri: lb://auth-service
          predicates:
            - Path=/auth/v3/api-docs,/auth/swagger-ui/**
          filters:
            - RewritePath=/auth/(?<segment>.*), /$\{segment}

        - id: book-service-swagger
          uri: lb://book-service
          predicates:
            - Path=/books/v3/api-docs,/books/swagger-ui/**
          filters:
            - RewritePath=/books/(?<segment>.*), /$\{segment}

        - id: exchange-service-swagger
          uri: lb://exchange-service
          predicates:
            - Path=/exchanges/v3/api-docs,/exchanges/swagger-ui/**
          filters:
            - RewritePath=/exchanges/(?<segment>.*), /$\{segment}

        - id: publication-service-swagger
          uri: lb://publication-service
          predicates:
            - Path=/publications/v3/api-docs,/publications/swagger-ui/**
          filters:
            - RewritePath=/publications/(?<segment>.*), /$\{segment}

      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:4200}"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              - PATCH
            allowedHeaders: "*"
            allowCredentials: true
            exposedHeaders:
              - X-Total-Count
              - Authorization
            maxAge: 3600

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    urls:
      - name: Auth Service
        url: /auth/v3/api-docs
      - name: Book Service
        url: /books/v3/api-docs
      - name: Exchange Service
        url: /exchanges/v3/api-docs
      - name: Publication Service
        url: /publications/v3/api-docs

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,gateway
  endpoint:
    health:
      show-details: always

logging:
  level:
    dev.petr.gateway: DEBUG
    org.springframework.cloud.gateway: DEBUG