server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/v1/auth/**

        - id: book-service
          uri: lb://book-service
          predicates:
            - Path=/api/v1/books/**,/api/v1/genres/**
          filters:
            - JwtAuthenticationFilter

        - id: exchange-service
          uri: lb://exchange-service
          predicates:
            - Path=/api/v1/exchanges/**
          filters:
            - JwtAuthenticationFilter

        - id: publication-service
          uri: lb://publication-service
          predicates:
            - Path=/api/v1/publications/**
          filters:
            - JwtAuthenticationFilter

        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/v1/notifications/**
          filters:
            - JwtAuthenticationFilter

        - id: notification-websocket
          uri: lb://notification-service
          predicates:
            - Path=/ws/notifications/**

        - id: auth-service-docs
          uri: lb://auth-service
          predicates:
            - Path=/auth/v3/api-docs
          filters:
            - RewritePath=/auth/v3/api-docs, /v3/api-docs

        - id: book-service-docs
          uri: lb://book-service
          predicates:
            - Path=/books/v3/api-docs
          filters:
            - RewritePath=/books/v3/api-docs, /v3/api-docs

        - id: exchange-service-docs
          uri: lb://exchange-service
          predicates:
            - Path=/exchanges/v3/api-docs
          filters:
            - RewritePath=/exchanges/v3/api-docs, /v3/api-docs

        - id: publication-service-docs
          uri: lb://publication-service
          predicates:
            - Path=/publications/v3/api-docs
          filters:
            - RewritePath=/publications/v3/api-docs, /v3/api-docs

        - id: notification-service-docs
          uri: lb://notification-service
          predicates:
            - Path=/notifications/v3/api-docs
          filters:
            - RewritePath=/notifications/v3/api-docs, /v3/api-docs

      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:4200}"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              - PATCH
            allowedHeaders: "*"
            allowCredentials: true
            exposedHeaders:
              - X-Total-Count
              - Authorization
            maxAge: 3600

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    urls:
      - name: Auth Service
        url: /auth/v3/api-docs
      - name: Book Service
        url: /books/v3/api-docs
      - name: Exchange Service
        url: /exchanges/v3/api-docs
      - name: Publication Service
        url: /publications/v3/api-docs
      - name: Notification Service
        url: /notifications/v3/api-docs

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,gateway

logging:
  level:
    dev.petr.gateway: DEBUG
    org.springframework.cloud.gateway: DEBUG